import Vue from 'vue';
import PrimeVue from 'primevue/config';

Vue.use(PrimeVue, {
  locale: {
    startsWith: '시작',
    contains: '포함',
    notContains: '포함하지 않음',
    endsWith: '끝',
    equals: '같음',
    notEquals: '같지 않음',
    noFilter: '필터 없음',
    lt: '보다 작음',
    lte: '보다 작거나 같음',
    gt: '보다 큼',
    gte: '보다 크거나 같음',
    dateIs: '날짜가 같음',
    dateIsNot: '날짜가 같지 않음',
    dateBefore: '이전 날짜',
    dateAfter: '이후 날짜',
    clear: '지우기',
    apply: '적용',
    matchAll: '모두 일치',
    matchAny: '아무거나 일치',
    addRule: '규칙 추가',
    removeRule: '규칙 제거',
    accept: '확인',
    reject: '취소',
    choose: '선택',
    upload: '업로드',
    cancel: '취소',
    dayNames: ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],
    dayNamesShort: ['일', '월', '화', '수', '목', '금', '토'],
    dayNamesMin: ['일', '월', '화', '수', '목', '금', '토'],
    monthNames: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    monthNamesShort: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    dateFormat: 'yy-mm-dd',
    firstDayOfWeek: 0,
    today: '오늘',
    weekHeader: '주',
    weak: '약함',
    medium: '보통',
    strong: '강함',
    passwordPrompt: '비밀번호를 입력하세요',
    emptyFilterMessage: '검색 결과가 없습니다.',
    emptyMessage: '사용 가능한 옵션이 없습니다.',
    aria: {
      trueLabel: '참',
      falseLabel: '거짓',
      nullLabel: '선택되지 않음',
      star: '1점',
      stars: '{star}점',
      selectAll: '모든 항목 선택',
      unselectAll: '모든 항목 선택 해제',
      close: '닫기',
      previous: '이전',
      next: '다음',
      navigation: '탐색',
      scrollTop: '맨 위로 스크롤',
      moveTop: '맨 위로 이동',
      moveUp: '위로 이동',
      moveDown: '아래로 이동',
      moveBottom: '맨 아래로 이동',
      moveToTarget: '목표로 이동',
      moveToSource: '소스로 이동',
      moveAllToTarget: '모두 목표로 이동',
      moveAllToSource: '모두 소스로 이동',
      pageLabel: '{page}',
      firstPageLabel: '첫 페이지',
      lastPageLabel: '마지막 페이지',
      nextPageLabel: '다음 페이지',
      previousPageLabel: '이전 페이지',
      rowsPerPageLabel: '페이지당 행 수',
      jumpToPageDropdownLabel: '페이지 드롭다운으로 이동',
      jumpToPageInputLabel: '페이지 입력으로 이동',
      selectRow: '행 선택',
      unselectRow: '행 선택 해제',
      expandRow: '행 확장',
      collapseRow: '행 축소',
      showFilterMenu: '필터 메뉴 보기',
      hideFilterMenu: '필터 메뉴 숨기기',
      filterOperator: '필터 연산자',
      filterConstraint: '필터 제약 조건',
      editRow: '행 편집',
      saveEdit: '편집 저장',
      cancelEdit: '편집 취소',
      listView: '리스트 보기',
      gridView: '그리드 보기',
      slide: '슬라이드',
      slideNumber: '{slideNumber}',
      zoomImage: '이미지 확대',
      zoomIn: '확대',
      zoomOut: '축소',
      rotateRight: '오른쪽으로 회전',
      rotateLeft: '왼쪽으로 회전',
    },
  },
});
