
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'LicenseStatus': typeof import("../domains/skill/roadmap/components/LicenseStatus.vue")['default']
    'LicenseStatusContents': typeof import("../domains/skill/roadmap/components/LicenseStatusContents.vue")['default']
    'LicenseStatusContentsItem': typeof import("../domains/skill/roadmap/components/LicenseStatusContentsItem.vue")['default']
    'RoadmapBranchSearchDialog': typeof import("../domains/skill/roadmap/components/RoadmapBranchSearchDialog.vue")['default']
    'RoadmapBranchStatistics': typeof import("../domains/skill/roadmap/components/RoadmapBranchStatistics.vue")['default']
    'RoadmapBranchStatisticsList': typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsList.vue")['default']
    'RoadmapBranchStatisticsSpecialCategory': typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsSpecialCategory.vue")['default']
    'RoadmapHistory': typeof import("../domains/skill/roadmap/components/RoadmapHistory.vue")['default']
    'RoadmapHistoryCourseList': typeof import("../domains/skill/roadmap/components/RoadmapHistoryCourseList.vue")['default']
    'RoadmapHistoryLicenseList': typeof import("../domains/skill/roadmap/components/RoadmapHistoryLicenseList.vue")['default']
    'RoadmapStatus': typeof import("../domains/skill/roadmap/components/RoadmapStatus.vue")['default']
    'RoadmapStatus1LevelItem': typeof import("../domains/skill/roadmap/components/RoadmapStatus1LevelItem.vue")['default']
    'RoadmapStatus2LevelItem': typeof import("../domains/skill/roadmap/components/RoadmapStatus2LevelItem.vue")['default']
    'RoadmapStatus3LevelItem': typeof import("../domains/skill/roadmap/components/RoadmapStatus3LevelItem.vue")['default']
    'RoadmapStatusContents': typeof import("../domains/skill/roadmap/components/RoadmapStatusContents.vue")['default']
    'RoadmapStatusSkillItem': typeof import("../domains/skill/roadmap/components/RoadmapStatusSkillItem.vue")['default']
    'CalendarDetailDialog': typeof import("../domains/myLearn/calendar/components/CalendarDetailDialog.vue")['default']
    'MyStudyCalendar': typeof import("../domains/myLearn/calendar/components/MyStudyCalendar.vue")['default']
    'AddressSearchDialog': typeof import("../domains/course/education/components/AddressSearchDialog.vue")['default']
    'AuthMemberUserDialog': typeof import("../domains/course/education/components/AuthMemberUserDialog.vue")['default']
    'CourseEducation': typeof import("../domains/course/education/components/CourseEducation.vue")['default']
    'CourseEducationAttatchmentDialog': typeof import("../domains/course/education/components/CourseEducationAttatchmentDialog.vue")['default']
    'CourseEducationDetail': typeof import("../domains/course/education/components/CourseEducationDetail.vue")['default']
    'CourseEducationPreviewDialog': typeof import("../domains/course/education/components/CourseEducationPreviewDialog.vue")['default']
    'CourseEducationRequestDialog': typeof import("../domains/course/education/components/CourseEducationRequestDialog.vue")['default']
    'BoardComment': typeof import("../domains/common/board/components/BoardComment.vue")['default']
    'BoardDialog': typeof import("../domains/common/board/components/BoardDialog.vue")['default']
    'TotalSearchManage': typeof import("../domains/totalsearch/components/TotalSearchManage.vue")['default']
    'Faq': typeof import("../domains/support/components/Faq.vue")['default']
    'Question': typeof import("../domains/support/components/Question.vue")['default']
    'SocialBoardComments': typeof import("../domains/social/components/SocialBoardComments.vue")['default']
    'SocialBoardCommentsForm': typeof import("../domains/social/components/SocialBoardCommentsForm.vue")['default']
    'SocialBoardCommentsItem': typeof import("../domains/social/components/SocialBoardCommentsItem.vue")['default']
    'SocialBoardCommentsItemContents': typeof import("../domains/social/components/SocialBoardCommentsItemContents.vue")['default']
    'SocialBoardContentsBestLargeItem': typeof import("../domains/social/components/SocialBoardContentsBestLargeItem.vue")['default']
    'SocialBoardContentsBestSmallItem': typeof import("../domains/social/components/SocialBoardContentsBestSmallItem.vue")['default']
    'SocialBoardContentsItem': typeof import("../domains/social/components/SocialBoardContentsItem.vue")['default']
    'SocialBoardContentsRankSmallItem': typeof import("../domains/social/components/SocialBoardContentsRankSmallItem.vue")['default']
    'SocialBoardNoticeDialog': typeof import("../domains/social/components/SocialBoardNoticeDialog.vue")['default']
    'CostApplyDetailDialog': typeof import("../domains/skill/components/CostApplyDetailDialog.vue")['default']
    'CostApplyDialog': typeof import("../domains/skill/components/CostApplyDialog.vue")['default']
    'CostApplyStatusDialog': typeof import("../domains/skill/components/CostApplyStatusDialog.vue")['default']
    'CostEduDetailTab': typeof import("../domains/skill/components/CostEduDetailTab.vue")['default']
    'CostEduTab': typeof import("../domains/skill/components/CostEduTab.vue")['default']
    'CostEmploymentDetailTab': typeof import("../domains/skill/components/CostEmploymentDetailTab.vue")['default']
    'CostEmploymentTab': typeof import("../domains/skill/components/CostEmploymentTab.vue")['default']
    'CostExamDetailTab': typeof import("../domains/skill/components/CostExamDetailTab.vue")['default']
    'CostExamTab': typeof import("../domains/skill/components/CostExamTab.vue")['default']
    'CourseRegister': typeof import("../domains/skill/components/CourseRegister.vue")['default']
    'ExpenseRegister': typeof import("../domains/skill/components/ExpenseRegister.vue")['default']
    'LanguageRegister': typeof import("../domains/skill/components/LanguageRegister.vue")['default']
    'LicenseRegister': typeof import("../domains/skill/components/LicenseRegister.vue")['default']
    'Roadmap': typeof import("../domains/skill/components/Roadmap.vue")['default']
    'RoadmapBranchStatisticsState': typeof import("../domains/skill/components/RoadmapBranchStatisticsState.vue")['default']
    'ScholarshipRegister': typeof import("../domains/skill/components/ScholarshipRegister.vue")['default']
    'SkillCourseItem': typeof import("../domains/skill/components/SkillCourseItem.vue")['default']
    'SkillCourseListDialog': typeof import("../domains/skill/components/SkillCourseListDialog.vue")['default']
    'SupplyLicenseDetailDialog': typeof import("../domains/skill/components/SupplyLicenseDetailDialog.vue")['default']
    'SupplyLicenseDialog': typeof import("../domains/skill/components/SupplyLicenseDialog.vue")['default']
    'SupportApproval': typeof import("../domains/skill/components/SupportApproval.vue")['default']
    'SupportItem': typeof import("../domains/skill/components/SupportItem.vue")['default']
    'SupportRegister': typeof import("../domains/skill/components/SupportRegister.vue")['default']
    'SupportReject': typeof import("../domains/skill/components/SupportReject.vue")['default']
    'WelfareFeeDialog': typeof import("../domains/skill/components/WelfareFeeDialog.vue")['default']
    'MyLearn': typeof import("../domains/myLearn/components/MyLearn.vue")['default']
    'MyLearnChangeDegreeDialog': typeof import("../domains/myLearn/components/MyLearnChangeDegreeDialog.vue")['default']
    'MyLearnHistory': typeof import("../domains/myLearn/components/MyLearnHistory.vue")['default']
    'MyLearnHistoryPrintDialog': typeof import("../domains/myLearn/components/MyLearnHistoryPrintDialog.vue")['default']
    'MyLearnHistoryTable': typeof import("../domains/myLearn/components/MyLearnHistoryTable.vue")['default']
    'MyLearnMain': typeof import("../domains/myLearn/components/MyLearnMain.vue")['default']
    'MyLearnMainRoadmapChart': typeof import("../domains/myLearn/components/MyLearnMainRoadmapChart.vue")['default']
    'MyLearnMainRoadmapDetailChart': typeof import("../domains/myLearn/components/MyLearnMainRoadmapDetailChart.vue")['default']
    'MyLearnProduct': typeof import("../domains/myLearn/components/MyLearnProduct.vue")['default']
    'MyLearnRepresentativeSkillDialog': typeof import("../domains/myLearn/components/MyLearnRepresentativeSkillDialog.vue")['default']
    'MyLearnReviewDialog': typeof import("../domains/myLearn/components/MyLearnReviewDialog.vue")['default']
    'MyLearnReviewFormDialog': typeof import("../domains/myLearn/components/MyLearnReviewFormDialog.vue")['default']
    'MyLearnReviewItem': typeof import("../domains/myLearn/components/MyLearnReviewItem.vue")['default']
    'MyLearnReviewList': typeof import("../domains/myLearn/components/MyLearnReviewList.vue")['default']
    'MyLearnUserInfoDialog': typeof import("../domains/myLearn/components/MyLearnUserInfoDialog.vue")['default']
    'MileageApplyDialog': typeof import("../domains/mileage/components/MileageApplyDialog.vue")['default']
    'MileageApplyHistoryTab': typeof import("../domains/mileage/components/MileageApplyHistoryTab.vue")['default']
    'MileageHistoryTab': typeof import("../domains/mileage/components/MileageHistoryTab.vue")['default']
    'Main': typeof import("../domains/main/components/Main.vue")['default']
    'MainCourseItem': typeof import("../domains/main/components/MainCourseItem.vue")['default']
    'MainCourseSchedule': typeof import("../domains/main/components/MainCourseSchedule.vue")['default']
    'MainMyCourseDegreeItem': typeof import("../domains/main/components/MainMyCourseDegreeItem.vue")['default']
    'MainMyInfo': typeof import("../domains/main/components/MainMyInfo.vue")['default']
    'MainMyInfoLibraryItem': typeof import("../domains/main/components/MainMyInfoLibraryItem.vue")['default']
    'MainNotice': typeof import("../domains/main/components/MainNotice.vue")['default']
    'MainPopularCourse': typeof import("../domains/main/components/MainPopularCourse.vue")['default']
    'MainPopupDialog': typeof import("../domains/main/components/MainPopupDialog.vue")['default']
    'MainQuestionDialog': typeof import("../domains/main/components/MainQuestionDialog.vue")['default']
    'MainQuickMenu': typeof import("../domains/main/components/MainQuickMenu.vue")['default']
    'MainQuickMenuItem': typeof import("../domains/main/components/MainQuickMenuItem.vue")['default']
    'MainRecentCourse': typeof import("../domains/main/components/MainRecentCourse.vue")['default']
    'MainReview': typeof import("../domains/main/components/MainReview.vue")['default']
    'MainTopBanner': typeof import("../domains/main/components/MainTopBanner.vue")['default']
    'SlideBanner': typeof import("../domains/main/components/SlideBanner.vue")['default']
    'SlideBannerItem': typeof import("../domains/main/components/SlideBannerItem.vue")['default']
    'AttendanceQrCode': typeof import("../domains/learning/components/AttendanceQrCode.vue")['default']
    'AttendanceQrCodeIntroPage': typeof import("../domains/learning/components/AttendanceQrCodeIntroPage.vue")['default']
    'LearnAttendanceQrCodeDialog': typeof import("../domains/learning/components/LearnAttendanceQrCodeDialog.vue")['default']
    'LearningExternal': typeof import("../domains/learning/components/LearningExternal.vue")['default']
    'LearningGroup': typeof import("../domains/learning/components/LearningGroup.vue")['default']
    'LearningLive': typeof import("../domains/learning/components/LearningLive.vue")['default']
    'LearningMain': typeof import("../domains/learning/components/LearningMain.vue")['default']
    'LearningPdf': typeof import("../domains/learning/components/LearningPdf.vue")['default']
    'LearningReport': typeof import("../domains/learning/components/LearningReport.vue")['default']
    'LearningSurvey': typeof import("../domains/learning/components/LearningSurvey.vue")['default']
    'LearningTest': typeof import("../domains/learning/components/LearningTest.vue")['default']
    'LearningVod': typeof import("../domains/learning/components/LearningVod.vue")['default']
    'StudyRoomMain': typeof import("../domains/learning/components/StudyRoomMain.vue")['default']
    'TitleBar': typeof import("../domains/learning/components/TitleBar.vue")['default']
    'ClassRoomApplyTab': typeof import("../domains/facility/components/ClassRoomApplyTab.vue")['default']
    'ClassRoomDetailTab': typeof import("../domains/facility/components/ClassRoomDetailTab.vue")['default']
    'FacilityRequestDialog': typeof import("../domains/facility/components/FacilityRequestDialog.vue")['default']
    'ResortFacilityRequestDialog': typeof import("../domains/facility/components/ResortFacilityRequestDialog.vue")['default']
    'StudioApplyTab': typeof import("../domains/facility/components/StudioApplyTab.vue")['default']
    'StudioDetailTab': typeof import("../domains/facility/components/StudioDetailTab.vue")['default']
    'StudioRequestDialog': typeof import("../domains/facility/components/StudioRequestDialog.vue")['default']
    'TrainingApplyTab': typeof import("../domains/facility/components/TrainingApplyTab.vue")['default']
    'TrainingDetailTab': typeof import("../domains/facility/components/TrainingDetailTab.vue")['default']
    'Community': typeof import("../domains/community/components/Community.vue")['default']
    'CommunityBoardComments': typeof import("../domains/community/components/CommunityBoardComments.vue")['default']
    'CommunityBoardCommentsForm': typeof import("../domains/community/components/CommunityBoardCommentsForm.vue")['default']
    'CommunityBoardCommentsItem': typeof import("../domains/community/components/CommunityBoardCommentsItem.vue")['default']
    'CommunityBoardCommentsItemContents': typeof import("../domains/community/components/CommunityBoardCommentsItemContents.vue")['default']
    'CommunityBoardContentsDetail': typeof import("../domains/community/components/CommunityBoardContentsDetail.vue")['default']
    'CommunityBoardContentsItem': typeof import("../domains/community/components/CommunityBoardContentsItem.vue")['default']
    'CommunitySurveyContentsItem': typeof import("../domains/community/components/CommunitySurveyContentsItem.vue")['default']
    'CommunitySurveyDetailDialog': typeof import("../domains/community/components/CommunitySurveyDetailDialog.vue")['default']
    'AppDownload': typeof import("../domains/auth/components/AppDownload.vue")['default']
    'Auth': typeof import("../domains/auth/components/Auth.vue")['default']
    'PasswordFind': typeof import("../domains/auth/components/PasswordFind.vue")['default']
    'User': typeof import("../domains/auth/components/User.vue")['default']
    'Approval': typeof import("../domains/approval/components/Approval.vue")['default']
    'ApprovalDetail': typeof import("../domains/approval/components/ApprovalDetail.vue")['default']
    'AlertDialog': typeof import("../components/AlertDialog.vue")['default']
    'AppAlert': typeof import("../components/AppAlert.vue")['default']
    'AppConfirm': typeof import("../components/AppConfirm.vue")['default']
    'AppPagination': typeof import("../components/AppPagination.vue")['default']
    'CommonFileUploader': typeof import("../components/CommonFileUploader.vue")['default']
    'CommonQrCode': typeof import("../components/CommonQrCode.vue")['default']
    'FileUploadForm': typeof import("../components/FileUploadForm.vue")['default']
    'FileUploadFormWithDropdown': typeof import("../components/FileUploadFormWithDropdown.vue")['default']
    'Log': typeof import("../components/Log.vue")['default']
    'PageGridWithPaging2': typeof import("../components/PageGridWithPaging2.vue")['default']
    'SwiperControls': typeof import("../components/SwiperControls.vue")['default']
    'CustomErrorMessage': typeof import("../components/custom/ErrorMessage.vue")['default']
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'PubComent': typeof import("../components/pubComent.vue")['default']
    'PubMypageHead': typeof import("../components/pubMypageHead.vue")['default']
    'PubProduct': typeof import("../components/pubProduct.vue")['default']
    'PubProduct02': typeof import("../components/pubProduct02.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtSnackbar': typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyLicenseStatus': typeof import("../domains/skill/roadmap/components/LicenseStatus.vue")['default']
    'LazyLicenseStatusContents': typeof import("../domains/skill/roadmap/components/LicenseStatusContents.vue")['default']
    'LazyLicenseStatusContentsItem': typeof import("../domains/skill/roadmap/components/LicenseStatusContentsItem.vue")['default']
    'LazyRoadmapBranchSearchDialog': typeof import("../domains/skill/roadmap/components/RoadmapBranchSearchDialog.vue")['default']
    'LazyRoadmapBranchStatistics': typeof import("../domains/skill/roadmap/components/RoadmapBranchStatistics.vue")['default']
    'LazyRoadmapBranchStatisticsList': typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsList.vue")['default']
    'LazyRoadmapBranchStatisticsSpecialCategory': typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsSpecialCategory.vue")['default']
    'LazyRoadmapHistory': typeof import("../domains/skill/roadmap/components/RoadmapHistory.vue")['default']
    'LazyRoadmapHistoryCourseList': typeof import("../domains/skill/roadmap/components/RoadmapHistoryCourseList.vue")['default']
    'LazyRoadmapHistoryLicenseList': typeof import("../domains/skill/roadmap/components/RoadmapHistoryLicenseList.vue")['default']
    'LazyRoadmapStatus': typeof import("../domains/skill/roadmap/components/RoadmapStatus.vue")['default']
    'LazyRoadmapStatus1LevelItem': typeof import("../domains/skill/roadmap/components/RoadmapStatus1LevelItem.vue")['default']
    'LazyRoadmapStatus2LevelItem': typeof import("../domains/skill/roadmap/components/RoadmapStatus2LevelItem.vue")['default']
    'LazyRoadmapStatus3LevelItem': typeof import("../domains/skill/roadmap/components/RoadmapStatus3LevelItem.vue")['default']
    'LazyRoadmapStatusContents': typeof import("../domains/skill/roadmap/components/RoadmapStatusContents.vue")['default']
    'LazyRoadmapStatusSkillItem': typeof import("../domains/skill/roadmap/components/RoadmapStatusSkillItem.vue")['default']
    'LazyCalendarDetailDialog': typeof import("../domains/myLearn/calendar/components/CalendarDetailDialog.vue")['default']
    'LazyMyStudyCalendar': typeof import("../domains/myLearn/calendar/components/MyStudyCalendar.vue")['default']
    'LazyAddressSearchDialog': typeof import("../domains/course/education/components/AddressSearchDialog.vue")['default']
    'LazyAuthMemberUserDialog': typeof import("../domains/course/education/components/AuthMemberUserDialog.vue")['default']
    'LazyCourseEducation': typeof import("../domains/course/education/components/CourseEducation.vue")['default']
    'LazyCourseEducationAttatchmentDialog': typeof import("../domains/course/education/components/CourseEducationAttatchmentDialog.vue")['default']
    'LazyCourseEducationDetail': typeof import("../domains/course/education/components/CourseEducationDetail.vue")['default']
    'LazyCourseEducationPreviewDialog': typeof import("../domains/course/education/components/CourseEducationPreviewDialog.vue")['default']
    'LazyCourseEducationRequestDialog': typeof import("../domains/course/education/components/CourseEducationRequestDialog.vue")['default']
    'LazyBoardComment': typeof import("../domains/common/board/components/BoardComment.vue")['default']
    'LazyBoardDialog': typeof import("../domains/common/board/components/BoardDialog.vue")['default']
    'LazyTotalSearchManage': typeof import("../domains/totalsearch/components/TotalSearchManage.vue")['default']
    'LazyFaq': typeof import("../domains/support/components/Faq.vue")['default']
    'LazyQuestion': typeof import("../domains/support/components/Question.vue")['default']
    'LazySocialBoardComments': typeof import("../domains/social/components/SocialBoardComments.vue")['default']
    'LazySocialBoardCommentsForm': typeof import("../domains/social/components/SocialBoardCommentsForm.vue")['default']
    'LazySocialBoardCommentsItem': typeof import("../domains/social/components/SocialBoardCommentsItem.vue")['default']
    'LazySocialBoardCommentsItemContents': typeof import("../domains/social/components/SocialBoardCommentsItemContents.vue")['default']
    'LazySocialBoardContentsBestLargeItem': typeof import("../domains/social/components/SocialBoardContentsBestLargeItem.vue")['default']
    'LazySocialBoardContentsBestSmallItem': typeof import("../domains/social/components/SocialBoardContentsBestSmallItem.vue")['default']
    'LazySocialBoardContentsItem': typeof import("../domains/social/components/SocialBoardContentsItem.vue")['default']
    'LazySocialBoardContentsRankSmallItem': typeof import("../domains/social/components/SocialBoardContentsRankSmallItem.vue")['default']
    'LazySocialBoardNoticeDialog': typeof import("../domains/social/components/SocialBoardNoticeDialog.vue")['default']
    'LazyCostApplyDetailDialog': typeof import("../domains/skill/components/CostApplyDetailDialog.vue")['default']
    'LazyCostApplyDialog': typeof import("../domains/skill/components/CostApplyDialog.vue")['default']
    'LazyCostApplyStatusDialog': typeof import("../domains/skill/components/CostApplyStatusDialog.vue")['default']
    'LazyCostEduDetailTab': typeof import("../domains/skill/components/CostEduDetailTab.vue")['default']
    'LazyCostEduTab': typeof import("../domains/skill/components/CostEduTab.vue")['default']
    'LazyCostEmploymentDetailTab': typeof import("../domains/skill/components/CostEmploymentDetailTab.vue")['default']
    'LazyCostEmploymentTab': typeof import("../domains/skill/components/CostEmploymentTab.vue")['default']
    'LazyCostExamDetailTab': typeof import("../domains/skill/components/CostExamDetailTab.vue")['default']
    'LazyCostExamTab': typeof import("../domains/skill/components/CostExamTab.vue")['default']
    'LazyCourseRegister': typeof import("../domains/skill/components/CourseRegister.vue")['default']
    'LazyExpenseRegister': typeof import("../domains/skill/components/ExpenseRegister.vue")['default']
    'LazyLanguageRegister': typeof import("../domains/skill/components/LanguageRegister.vue")['default']
    'LazyLicenseRegister': typeof import("../domains/skill/components/LicenseRegister.vue")['default']
    'LazyRoadmap': typeof import("../domains/skill/components/Roadmap.vue")['default']
    'LazyRoadmapBranchStatisticsState': typeof import("../domains/skill/components/RoadmapBranchStatisticsState.vue")['default']
    'LazyScholarshipRegister': typeof import("../domains/skill/components/ScholarshipRegister.vue")['default']
    'LazySkillCourseItem': typeof import("../domains/skill/components/SkillCourseItem.vue")['default']
    'LazySkillCourseListDialog': typeof import("../domains/skill/components/SkillCourseListDialog.vue")['default']
    'LazySupplyLicenseDetailDialog': typeof import("../domains/skill/components/SupplyLicenseDetailDialog.vue")['default']
    'LazySupplyLicenseDialog': typeof import("../domains/skill/components/SupplyLicenseDialog.vue")['default']
    'LazySupportApproval': typeof import("../domains/skill/components/SupportApproval.vue")['default']
    'LazySupportItem': typeof import("../domains/skill/components/SupportItem.vue")['default']
    'LazySupportRegister': typeof import("../domains/skill/components/SupportRegister.vue")['default']
    'LazySupportReject': typeof import("../domains/skill/components/SupportReject.vue")['default']
    'LazyWelfareFeeDialog': typeof import("../domains/skill/components/WelfareFeeDialog.vue")['default']
    'LazyMyLearn': typeof import("../domains/myLearn/components/MyLearn.vue")['default']
    'LazyMyLearnChangeDegreeDialog': typeof import("../domains/myLearn/components/MyLearnChangeDegreeDialog.vue")['default']
    'LazyMyLearnHistory': typeof import("../domains/myLearn/components/MyLearnHistory.vue")['default']
    'LazyMyLearnHistoryPrintDialog': typeof import("../domains/myLearn/components/MyLearnHistoryPrintDialog.vue")['default']
    'LazyMyLearnHistoryTable': typeof import("../domains/myLearn/components/MyLearnHistoryTable.vue")['default']
    'LazyMyLearnMain': typeof import("../domains/myLearn/components/MyLearnMain.vue")['default']
    'LazyMyLearnMainRoadmapChart': typeof import("../domains/myLearn/components/MyLearnMainRoadmapChart.vue")['default']
    'LazyMyLearnMainRoadmapDetailChart': typeof import("../domains/myLearn/components/MyLearnMainRoadmapDetailChart.vue")['default']
    'LazyMyLearnProduct': typeof import("../domains/myLearn/components/MyLearnProduct.vue")['default']
    'LazyMyLearnRepresentativeSkillDialog': typeof import("../domains/myLearn/components/MyLearnRepresentativeSkillDialog.vue")['default']
    'LazyMyLearnReviewDialog': typeof import("../domains/myLearn/components/MyLearnReviewDialog.vue")['default']
    'LazyMyLearnReviewFormDialog': typeof import("../domains/myLearn/components/MyLearnReviewFormDialog.vue")['default']
    'LazyMyLearnReviewItem': typeof import("../domains/myLearn/components/MyLearnReviewItem.vue")['default']
    'LazyMyLearnReviewList': typeof import("../domains/myLearn/components/MyLearnReviewList.vue")['default']
    'LazyMyLearnUserInfoDialog': typeof import("../domains/myLearn/components/MyLearnUserInfoDialog.vue")['default']
    'LazyMileageApplyDialog': typeof import("../domains/mileage/components/MileageApplyDialog.vue")['default']
    'LazyMileageApplyHistoryTab': typeof import("../domains/mileage/components/MileageApplyHistoryTab.vue")['default']
    'LazyMileageHistoryTab': typeof import("../domains/mileage/components/MileageHistoryTab.vue")['default']
    'LazyMain': typeof import("../domains/main/components/Main.vue")['default']
    'LazyMainCourseItem': typeof import("../domains/main/components/MainCourseItem.vue")['default']
    'LazyMainCourseSchedule': typeof import("../domains/main/components/MainCourseSchedule.vue")['default']
    'LazyMainMyCourseDegreeItem': typeof import("../domains/main/components/MainMyCourseDegreeItem.vue")['default']
    'LazyMainMyInfo': typeof import("../domains/main/components/MainMyInfo.vue")['default']
    'LazyMainMyInfoLibraryItem': typeof import("../domains/main/components/MainMyInfoLibraryItem.vue")['default']
    'LazyMainNotice': typeof import("../domains/main/components/MainNotice.vue")['default']
    'LazyMainPopularCourse': typeof import("../domains/main/components/MainPopularCourse.vue")['default']
    'LazyMainPopupDialog': typeof import("../domains/main/components/MainPopupDialog.vue")['default']
    'LazyMainQuestionDialog': typeof import("../domains/main/components/MainQuestionDialog.vue")['default']
    'LazyMainQuickMenu': typeof import("../domains/main/components/MainQuickMenu.vue")['default']
    'LazyMainQuickMenuItem': typeof import("../domains/main/components/MainQuickMenuItem.vue")['default']
    'LazyMainRecentCourse': typeof import("../domains/main/components/MainRecentCourse.vue")['default']
    'LazyMainReview': typeof import("../domains/main/components/MainReview.vue")['default']
    'LazyMainTopBanner': typeof import("../domains/main/components/MainTopBanner.vue")['default']
    'LazySlideBanner': typeof import("../domains/main/components/SlideBanner.vue")['default']
    'LazySlideBannerItem': typeof import("../domains/main/components/SlideBannerItem.vue")['default']
    'LazyAttendanceQrCode': typeof import("../domains/learning/components/AttendanceQrCode.vue")['default']
    'LazyAttendanceQrCodeIntroPage': typeof import("../domains/learning/components/AttendanceQrCodeIntroPage.vue")['default']
    'LazyLearnAttendanceQrCodeDialog': typeof import("../domains/learning/components/LearnAttendanceQrCodeDialog.vue")['default']
    'LazyLearningExternal': typeof import("../domains/learning/components/LearningExternal.vue")['default']
    'LazyLearningGroup': typeof import("../domains/learning/components/LearningGroup.vue")['default']
    'LazyLearningLive': typeof import("../domains/learning/components/LearningLive.vue")['default']
    'LazyLearningMain': typeof import("../domains/learning/components/LearningMain.vue")['default']
    'LazyLearningPdf': typeof import("../domains/learning/components/LearningPdf.vue")['default']
    'LazyLearningReport': typeof import("../domains/learning/components/LearningReport.vue")['default']
    'LazyLearningSurvey': typeof import("../domains/learning/components/LearningSurvey.vue")['default']
    'LazyLearningTest': typeof import("../domains/learning/components/LearningTest.vue")['default']
    'LazyLearningVod': typeof import("../domains/learning/components/LearningVod.vue")['default']
    'LazyStudyRoomMain': typeof import("../domains/learning/components/StudyRoomMain.vue")['default']
    'LazyTitleBar': typeof import("../domains/learning/components/TitleBar.vue")['default']
    'LazyClassRoomApplyTab': typeof import("../domains/facility/components/ClassRoomApplyTab.vue")['default']
    'LazyClassRoomDetailTab': typeof import("../domains/facility/components/ClassRoomDetailTab.vue")['default']
    'LazyFacilityRequestDialog': typeof import("../domains/facility/components/FacilityRequestDialog.vue")['default']
    'LazyResortFacilityRequestDialog': typeof import("../domains/facility/components/ResortFacilityRequestDialog.vue")['default']
    'LazyStudioApplyTab': typeof import("../domains/facility/components/StudioApplyTab.vue")['default']
    'LazyStudioDetailTab': typeof import("../domains/facility/components/StudioDetailTab.vue")['default']
    'LazyStudioRequestDialog': typeof import("../domains/facility/components/StudioRequestDialog.vue")['default']
    'LazyTrainingApplyTab': typeof import("../domains/facility/components/TrainingApplyTab.vue")['default']
    'LazyTrainingDetailTab': typeof import("../domains/facility/components/TrainingDetailTab.vue")['default']
    'LazyCommunity': typeof import("../domains/community/components/Community.vue")['default']
    'LazyCommunityBoardComments': typeof import("../domains/community/components/CommunityBoardComments.vue")['default']
    'LazyCommunityBoardCommentsForm': typeof import("../domains/community/components/CommunityBoardCommentsForm.vue")['default']
    'LazyCommunityBoardCommentsItem': typeof import("../domains/community/components/CommunityBoardCommentsItem.vue")['default']
    'LazyCommunityBoardCommentsItemContents': typeof import("../domains/community/components/CommunityBoardCommentsItemContents.vue")['default']
    'LazyCommunityBoardContentsDetail': typeof import("../domains/community/components/CommunityBoardContentsDetail.vue")['default']
    'LazyCommunityBoardContentsItem': typeof import("../domains/community/components/CommunityBoardContentsItem.vue")['default']
    'LazyCommunitySurveyContentsItem': typeof import("../domains/community/components/CommunitySurveyContentsItem.vue")['default']
    'LazyCommunitySurveyDetailDialog': typeof import("../domains/community/components/CommunitySurveyDetailDialog.vue")['default']
    'LazyAppDownload': typeof import("../domains/auth/components/AppDownload.vue")['default']
    'LazyAuth': typeof import("../domains/auth/components/Auth.vue")['default']
    'LazyPasswordFind': typeof import("../domains/auth/components/PasswordFind.vue")['default']
    'LazyUser': typeof import("../domains/auth/components/User.vue")['default']
    'LazyApproval': typeof import("../domains/approval/components/Approval.vue")['default']
    'LazyApprovalDetail': typeof import("../domains/approval/components/ApprovalDetail.vue")['default']
    'LazyAlertDialog': typeof import("../components/AlertDialog.vue")['default']
    'LazyAppAlert': typeof import("../components/AppAlert.vue")['default']
    'LazyAppConfirm': typeof import("../components/AppConfirm.vue")['default']
    'LazyAppPagination': typeof import("../components/AppPagination.vue")['default']
    'LazyCommonFileUploader': typeof import("../components/CommonFileUploader.vue")['default']
    'LazyCommonQrCode': typeof import("../components/CommonQrCode.vue")['default']
    'LazyFileUploadForm': typeof import("../components/FileUploadForm.vue")['default']
    'LazyFileUploadFormWithDropdown': typeof import("../components/FileUploadFormWithDropdown.vue")['default']
    'LazyLog': typeof import("../components/Log.vue")['default']
    'LazyPageGridWithPaging2': typeof import("../components/PageGridWithPaging2.vue")['default']
    'LazySwiperControls': typeof import("../components/SwiperControls.vue")['default']
    'LazyCustomErrorMessage': typeof import("../components/custom/ErrorMessage.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyLayoutHeader': typeof import("../components/layout/Header.vue")['default']
    'LazyPubComent': typeof import("../components/pubComent.vue")['default']
    'LazyPubMypageHead': typeof import("../components/pubMypageHead.vue")['default']
    'LazyPubProduct': typeof import("../components/pubProduct.vue")['default']
    'LazyPubProduct02': typeof import("../components/pubProduct02.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtSnackbar': typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const LicenseStatus: typeof import("../domains/skill/roadmap/components/LicenseStatus.vue")['default']
export const LicenseStatusContents: typeof import("../domains/skill/roadmap/components/LicenseStatusContents.vue")['default']
export const LicenseStatusContentsItem: typeof import("../domains/skill/roadmap/components/LicenseStatusContentsItem.vue")['default']
export const RoadmapBranchSearchDialog: typeof import("../domains/skill/roadmap/components/RoadmapBranchSearchDialog.vue")['default']
export const RoadmapBranchStatistics: typeof import("../domains/skill/roadmap/components/RoadmapBranchStatistics.vue")['default']
export const RoadmapBranchStatisticsList: typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsList.vue")['default']
export const RoadmapBranchStatisticsSpecialCategory: typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsSpecialCategory.vue")['default']
export const RoadmapHistory: typeof import("../domains/skill/roadmap/components/RoadmapHistory.vue")['default']
export const RoadmapHistoryCourseList: typeof import("../domains/skill/roadmap/components/RoadmapHistoryCourseList.vue")['default']
export const RoadmapHistoryLicenseList: typeof import("../domains/skill/roadmap/components/RoadmapHistoryLicenseList.vue")['default']
export const RoadmapStatus: typeof import("../domains/skill/roadmap/components/RoadmapStatus.vue")['default']
export const RoadmapStatus1LevelItem: typeof import("../domains/skill/roadmap/components/RoadmapStatus1LevelItem.vue")['default']
export const RoadmapStatus2LevelItem: typeof import("../domains/skill/roadmap/components/RoadmapStatus2LevelItem.vue")['default']
export const RoadmapStatus3LevelItem: typeof import("../domains/skill/roadmap/components/RoadmapStatus3LevelItem.vue")['default']
export const RoadmapStatusContents: typeof import("../domains/skill/roadmap/components/RoadmapStatusContents.vue")['default']
export const RoadmapStatusSkillItem: typeof import("../domains/skill/roadmap/components/RoadmapStatusSkillItem.vue")['default']
export const CalendarDetailDialog: typeof import("../domains/myLearn/calendar/components/CalendarDetailDialog.vue")['default']
export const MyStudyCalendar: typeof import("../domains/myLearn/calendar/components/MyStudyCalendar.vue")['default']
export const AddressSearchDialog: typeof import("../domains/course/education/components/AddressSearchDialog.vue")['default']
export const AuthMemberUserDialog: typeof import("../domains/course/education/components/AuthMemberUserDialog.vue")['default']
export const CourseEducation: typeof import("../domains/course/education/components/CourseEducation.vue")['default']
export const CourseEducationAttatchmentDialog: typeof import("../domains/course/education/components/CourseEducationAttatchmentDialog.vue")['default']
export const CourseEducationDetail: typeof import("../domains/course/education/components/CourseEducationDetail.vue")['default']
export const CourseEducationPreviewDialog: typeof import("../domains/course/education/components/CourseEducationPreviewDialog.vue")['default']
export const CourseEducationRequestDialog: typeof import("../domains/course/education/components/CourseEducationRequestDialog.vue")['default']
export const BoardComment: typeof import("../domains/common/board/components/BoardComment.vue")['default']
export const BoardDialog: typeof import("../domains/common/board/components/BoardDialog.vue")['default']
export const TotalSearchManage: typeof import("../domains/totalsearch/components/TotalSearchManage.vue")['default']
export const Faq: typeof import("../domains/support/components/Faq.vue")['default']
export const Question: typeof import("../domains/support/components/Question.vue")['default']
export const SocialBoardComments: typeof import("../domains/social/components/SocialBoardComments.vue")['default']
export const SocialBoardCommentsForm: typeof import("../domains/social/components/SocialBoardCommentsForm.vue")['default']
export const SocialBoardCommentsItem: typeof import("../domains/social/components/SocialBoardCommentsItem.vue")['default']
export const SocialBoardCommentsItemContents: typeof import("../domains/social/components/SocialBoardCommentsItemContents.vue")['default']
export const SocialBoardContentsBestLargeItem: typeof import("../domains/social/components/SocialBoardContentsBestLargeItem.vue")['default']
export const SocialBoardContentsBestSmallItem: typeof import("../domains/social/components/SocialBoardContentsBestSmallItem.vue")['default']
export const SocialBoardContentsItem: typeof import("../domains/social/components/SocialBoardContentsItem.vue")['default']
export const SocialBoardContentsRankSmallItem: typeof import("../domains/social/components/SocialBoardContentsRankSmallItem.vue")['default']
export const SocialBoardNoticeDialog: typeof import("../domains/social/components/SocialBoardNoticeDialog.vue")['default']
export const CostApplyDetailDialog: typeof import("../domains/skill/components/CostApplyDetailDialog.vue")['default']
export const CostApplyDialog: typeof import("../domains/skill/components/CostApplyDialog.vue")['default']
export const CostApplyStatusDialog: typeof import("../domains/skill/components/CostApplyStatusDialog.vue")['default']
export const CostEduDetailTab: typeof import("../domains/skill/components/CostEduDetailTab.vue")['default']
export const CostEduTab: typeof import("../domains/skill/components/CostEduTab.vue")['default']
export const CostEmploymentDetailTab: typeof import("../domains/skill/components/CostEmploymentDetailTab.vue")['default']
export const CostEmploymentTab: typeof import("../domains/skill/components/CostEmploymentTab.vue")['default']
export const CostExamDetailTab: typeof import("../domains/skill/components/CostExamDetailTab.vue")['default']
export const CostExamTab: typeof import("../domains/skill/components/CostExamTab.vue")['default']
export const CourseRegister: typeof import("../domains/skill/components/CourseRegister.vue")['default']
export const ExpenseRegister: typeof import("../domains/skill/components/ExpenseRegister.vue")['default']
export const LanguageRegister: typeof import("../domains/skill/components/LanguageRegister.vue")['default']
export const LicenseRegister: typeof import("../domains/skill/components/LicenseRegister.vue")['default']
export const Roadmap: typeof import("../domains/skill/components/Roadmap.vue")['default']
export const RoadmapBranchStatisticsState: typeof import("../domains/skill/components/RoadmapBranchStatisticsState.vue")['default']
export const ScholarshipRegister: typeof import("../domains/skill/components/ScholarshipRegister.vue")['default']
export const SkillCourseItem: typeof import("../domains/skill/components/SkillCourseItem.vue")['default']
export const SkillCourseListDialog: typeof import("../domains/skill/components/SkillCourseListDialog.vue")['default']
export const SupplyLicenseDetailDialog: typeof import("../domains/skill/components/SupplyLicenseDetailDialog.vue")['default']
export const SupplyLicenseDialog: typeof import("../domains/skill/components/SupplyLicenseDialog.vue")['default']
export const SupportApproval: typeof import("../domains/skill/components/SupportApproval.vue")['default']
export const SupportItem: typeof import("../domains/skill/components/SupportItem.vue")['default']
export const SupportRegister: typeof import("../domains/skill/components/SupportRegister.vue")['default']
export const SupportReject: typeof import("../domains/skill/components/SupportReject.vue")['default']
export const WelfareFeeDialog: typeof import("../domains/skill/components/WelfareFeeDialog.vue")['default']
export const MyLearn: typeof import("../domains/myLearn/components/MyLearn.vue")['default']
export const MyLearnChangeDegreeDialog: typeof import("../domains/myLearn/components/MyLearnChangeDegreeDialog.vue")['default']
export const MyLearnHistory: typeof import("../domains/myLearn/components/MyLearnHistory.vue")['default']
export const MyLearnHistoryPrintDialog: typeof import("../domains/myLearn/components/MyLearnHistoryPrintDialog.vue")['default']
export const MyLearnHistoryTable: typeof import("../domains/myLearn/components/MyLearnHistoryTable.vue")['default']
export const MyLearnMain: typeof import("../domains/myLearn/components/MyLearnMain.vue")['default']
export const MyLearnMainRoadmapChart: typeof import("../domains/myLearn/components/MyLearnMainRoadmapChart.vue")['default']
export const MyLearnMainRoadmapDetailChart: typeof import("../domains/myLearn/components/MyLearnMainRoadmapDetailChart.vue")['default']
export const MyLearnProduct: typeof import("../domains/myLearn/components/MyLearnProduct.vue")['default']
export const MyLearnRepresentativeSkillDialog: typeof import("../domains/myLearn/components/MyLearnRepresentativeSkillDialog.vue")['default']
export const MyLearnReviewDialog: typeof import("../domains/myLearn/components/MyLearnReviewDialog.vue")['default']
export const MyLearnReviewFormDialog: typeof import("../domains/myLearn/components/MyLearnReviewFormDialog.vue")['default']
export const MyLearnReviewItem: typeof import("../domains/myLearn/components/MyLearnReviewItem.vue")['default']
export const MyLearnReviewList: typeof import("../domains/myLearn/components/MyLearnReviewList.vue")['default']
export const MyLearnUserInfoDialog: typeof import("../domains/myLearn/components/MyLearnUserInfoDialog.vue")['default']
export const MileageApplyDialog: typeof import("../domains/mileage/components/MileageApplyDialog.vue")['default']
export const MileageApplyHistoryTab: typeof import("../domains/mileage/components/MileageApplyHistoryTab.vue")['default']
export const MileageHistoryTab: typeof import("../domains/mileage/components/MileageHistoryTab.vue")['default']
export const Main: typeof import("../domains/main/components/Main.vue")['default']
export const MainCourseItem: typeof import("../domains/main/components/MainCourseItem.vue")['default']
export const MainCourseSchedule: typeof import("../domains/main/components/MainCourseSchedule.vue")['default']
export const MainMyCourseDegreeItem: typeof import("../domains/main/components/MainMyCourseDegreeItem.vue")['default']
export const MainMyInfo: typeof import("../domains/main/components/MainMyInfo.vue")['default']
export const MainMyInfoLibraryItem: typeof import("../domains/main/components/MainMyInfoLibraryItem.vue")['default']
export const MainNotice: typeof import("../domains/main/components/MainNotice.vue")['default']
export const MainPopularCourse: typeof import("../domains/main/components/MainPopularCourse.vue")['default']
export const MainPopupDialog: typeof import("../domains/main/components/MainPopupDialog.vue")['default']
export const MainQuestionDialog: typeof import("../domains/main/components/MainQuestionDialog.vue")['default']
export const MainQuickMenu: typeof import("../domains/main/components/MainQuickMenu.vue")['default']
export const MainQuickMenuItem: typeof import("../domains/main/components/MainQuickMenuItem.vue")['default']
export const MainRecentCourse: typeof import("../domains/main/components/MainRecentCourse.vue")['default']
export const MainReview: typeof import("../domains/main/components/MainReview.vue")['default']
export const MainTopBanner: typeof import("../domains/main/components/MainTopBanner.vue")['default']
export const SlideBanner: typeof import("../domains/main/components/SlideBanner.vue")['default']
export const SlideBannerItem: typeof import("../domains/main/components/SlideBannerItem.vue")['default']
export const AttendanceQrCode: typeof import("../domains/learning/components/AttendanceQrCode.vue")['default']
export const AttendanceQrCodeIntroPage: typeof import("../domains/learning/components/AttendanceQrCodeIntroPage.vue")['default']
export const LearnAttendanceQrCodeDialog: typeof import("../domains/learning/components/LearnAttendanceQrCodeDialog.vue")['default']
export const LearningExternal: typeof import("../domains/learning/components/LearningExternal.vue")['default']
export const LearningGroup: typeof import("../domains/learning/components/LearningGroup.vue")['default']
export const LearningLive: typeof import("../domains/learning/components/LearningLive.vue")['default']
export const LearningMain: typeof import("../domains/learning/components/LearningMain.vue")['default']
export const LearningPdf: typeof import("../domains/learning/components/LearningPdf.vue")['default']
export const LearningReport: typeof import("../domains/learning/components/LearningReport.vue")['default']
export const LearningSurvey: typeof import("../domains/learning/components/LearningSurvey.vue")['default']
export const LearningTest: typeof import("../domains/learning/components/LearningTest.vue")['default']
export const LearningVod: typeof import("../domains/learning/components/LearningVod.vue")['default']
export const StudyRoomMain: typeof import("../domains/learning/components/StudyRoomMain.vue")['default']
export const TitleBar: typeof import("../domains/learning/components/TitleBar.vue")['default']
export const ClassRoomApplyTab: typeof import("../domains/facility/components/ClassRoomApplyTab.vue")['default']
export const ClassRoomDetailTab: typeof import("../domains/facility/components/ClassRoomDetailTab.vue")['default']
export const FacilityRequestDialog: typeof import("../domains/facility/components/FacilityRequestDialog.vue")['default']
export const ResortFacilityRequestDialog: typeof import("../domains/facility/components/ResortFacilityRequestDialog.vue")['default']
export const StudioApplyTab: typeof import("../domains/facility/components/StudioApplyTab.vue")['default']
export const StudioDetailTab: typeof import("../domains/facility/components/StudioDetailTab.vue")['default']
export const StudioRequestDialog: typeof import("../domains/facility/components/StudioRequestDialog.vue")['default']
export const TrainingApplyTab: typeof import("../domains/facility/components/TrainingApplyTab.vue")['default']
export const TrainingDetailTab: typeof import("../domains/facility/components/TrainingDetailTab.vue")['default']
export const Community: typeof import("../domains/community/components/Community.vue")['default']
export const CommunityBoardComments: typeof import("../domains/community/components/CommunityBoardComments.vue")['default']
export const CommunityBoardCommentsForm: typeof import("../domains/community/components/CommunityBoardCommentsForm.vue")['default']
export const CommunityBoardCommentsItem: typeof import("../domains/community/components/CommunityBoardCommentsItem.vue")['default']
export const CommunityBoardCommentsItemContents: typeof import("../domains/community/components/CommunityBoardCommentsItemContents.vue")['default']
export const CommunityBoardContentsDetail: typeof import("../domains/community/components/CommunityBoardContentsDetail.vue")['default']
export const CommunityBoardContentsItem: typeof import("../domains/community/components/CommunityBoardContentsItem.vue")['default']
export const CommunitySurveyContentsItem: typeof import("../domains/community/components/CommunitySurveyContentsItem.vue")['default']
export const CommunitySurveyDetailDialog: typeof import("../domains/community/components/CommunitySurveyDetailDialog.vue")['default']
export const AppDownload: typeof import("../domains/auth/components/AppDownload.vue")['default']
export const Auth: typeof import("../domains/auth/components/Auth.vue")['default']
export const PasswordFind: typeof import("../domains/auth/components/PasswordFind.vue")['default']
export const User: typeof import("../domains/auth/components/User.vue")['default']
export const Approval: typeof import("../domains/approval/components/Approval.vue")['default']
export const ApprovalDetail: typeof import("../domains/approval/components/ApprovalDetail.vue")['default']
export const AlertDialog: typeof import("../components/AlertDialog.vue")['default']
export const AppAlert: typeof import("../components/AppAlert.vue")['default']
export const AppConfirm: typeof import("../components/AppConfirm.vue")['default']
export const AppPagination: typeof import("../components/AppPagination.vue")['default']
export const CommonFileUploader: typeof import("../components/CommonFileUploader.vue")['default']
export const CommonQrCode: typeof import("../components/CommonQrCode.vue")['default']
export const FileUploadForm: typeof import("../components/FileUploadForm.vue")['default']
export const FileUploadFormWithDropdown: typeof import("../components/FileUploadFormWithDropdown.vue")['default']
export const Log: typeof import("../components/Log.vue")['default']
export const PageGridWithPaging2: typeof import("../components/PageGridWithPaging2.vue")['default']
export const SwiperControls: typeof import("../components/SwiperControls.vue")['default']
export const CustomErrorMessage: typeof import("../components/custom/ErrorMessage.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const PubComent: typeof import("../components/pubComent.vue")['default']
export const PubMypageHead: typeof import("../components/pubMypageHead.vue")['default']
export const PubProduct: typeof import("../components/pubProduct.vue")['default']
export const PubProduct02: typeof import("../components/pubProduct02.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtSnackbar: typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyLicenseStatus: typeof import("../domains/skill/roadmap/components/LicenseStatus.vue")['default']
export const LazyLicenseStatusContents: typeof import("../domains/skill/roadmap/components/LicenseStatusContents.vue")['default']
export const LazyLicenseStatusContentsItem: typeof import("../domains/skill/roadmap/components/LicenseStatusContentsItem.vue")['default']
export const LazyRoadmapBranchSearchDialog: typeof import("../domains/skill/roadmap/components/RoadmapBranchSearchDialog.vue")['default']
export const LazyRoadmapBranchStatistics: typeof import("../domains/skill/roadmap/components/RoadmapBranchStatistics.vue")['default']
export const LazyRoadmapBranchStatisticsList: typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsList.vue")['default']
export const LazyRoadmapBranchStatisticsSpecialCategory: typeof import("../domains/skill/roadmap/components/RoadmapBranchStatisticsSpecialCategory.vue")['default']
export const LazyRoadmapHistory: typeof import("../domains/skill/roadmap/components/RoadmapHistory.vue")['default']
export const LazyRoadmapHistoryCourseList: typeof import("../domains/skill/roadmap/components/RoadmapHistoryCourseList.vue")['default']
export const LazyRoadmapHistoryLicenseList: typeof import("../domains/skill/roadmap/components/RoadmapHistoryLicenseList.vue")['default']
export const LazyRoadmapStatus: typeof import("../domains/skill/roadmap/components/RoadmapStatus.vue")['default']
export const LazyRoadmapStatus1LevelItem: typeof import("../domains/skill/roadmap/components/RoadmapStatus1LevelItem.vue")['default']
export const LazyRoadmapStatus2LevelItem: typeof import("../domains/skill/roadmap/components/RoadmapStatus2LevelItem.vue")['default']
export const LazyRoadmapStatus3LevelItem: typeof import("../domains/skill/roadmap/components/RoadmapStatus3LevelItem.vue")['default']
export const LazyRoadmapStatusContents: typeof import("../domains/skill/roadmap/components/RoadmapStatusContents.vue")['default']
export const LazyRoadmapStatusSkillItem: typeof import("../domains/skill/roadmap/components/RoadmapStatusSkillItem.vue")['default']
export const LazyCalendarDetailDialog: typeof import("../domains/myLearn/calendar/components/CalendarDetailDialog.vue")['default']
export const LazyMyStudyCalendar: typeof import("../domains/myLearn/calendar/components/MyStudyCalendar.vue")['default']
export const LazyAddressSearchDialog: typeof import("../domains/course/education/components/AddressSearchDialog.vue")['default']
export const LazyAuthMemberUserDialog: typeof import("../domains/course/education/components/AuthMemberUserDialog.vue")['default']
export const LazyCourseEducation: typeof import("../domains/course/education/components/CourseEducation.vue")['default']
export const LazyCourseEducationAttatchmentDialog: typeof import("../domains/course/education/components/CourseEducationAttatchmentDialog.vue")['default']
export const LazyCourseEducationDetail: typeof import("../domains/course/education/components/CourseEducationDetail.vue")['default']
export const LazyCourseEducationPreviewDialog: typeof import("../domains/course/education/components/CourseEducationPreviewDialog.vue")['default']
export const LazyCourseEducationRequestDialog: typeof import("../domains/course/education/components/CourseEducationRequestDialog.vue")['default']
export const LazyBoardComment: typeof import("../domains/common/board/components/BoardComment.vue")['default']
export const LazyBoardDialog: typeof import("../domains/common/board/components/BoardDialog.vue")['default']
export const LazyTotalSearchManage: typeof import("../domains/totalsearch/components/TotalSearchManage.vue")['default']
export const LazyFaq: typeof import("../domains/support/components/Faq.vue")['default']
export const LazyQuestion: typeof import("../domains/support/components/Question.vue")['default']
export const LazySocialBoardComments: typeof import("../domains/social/components/SocialBoardComments.vue")['default']
export const LazySocialBoardCommentsForm: typeof import("../domains/social/components/SocialBoardCommentsForm.vue")['default']
export const LazySocialBoardCommentsItem: typeof import("../domains/social/components/SocialBoardCommentsItem.vue")['default']
export const LazySocialBoardCommentsItemContents: typeof import("../domains/social/components/SocialBoardCommentsItemContents.vue")['default']
export const LazySocialBoardContentsBestLargeItem: typeof import("../domains/social/components/SocialBoardContentsBestLargeItem.vue")['default']
export const LazySocialBoardContentsBestSmallItem: typeof import("../domains/social/components/SocialBoardContentsBestSmallItem.vue")['default']
export const LazySocialBoardContentsItem: typeof import("../domains/social/components/SocialBoardContentsItem.vue")['default']
export const LazySocialBoardContentsRankSmallItem: typeof import("../domains/social/components/SocialBoardContentsRankSmallItem.vue")['default']
export const LazySocialBoardNoticeDialog: typeof import("../domains/social/components/SocialBoardNoticeDialog.vue")['default']
export const LazyCostApplyDetailDialog: typeof import("../domains/skill/components/CostApplyDetailDialog.vue")['default']
export const LazyCostApplyDialog: typeof import("../domains/skill/components/CostApplyDialog.vue")['default']
export const LazyCostApplyStatusDialog: typeof import("../domains/skill/components/CostApplyStatusDialog.vue")['default']
export const LazyCostEduDetailTab: typeof import("../domains/skill/components/CostEduDetailTab.vue")['default']
export const LazyCostEduTab: typeof import("../domains/skill/components/CostEduTab.vue")['default']
export const LazyCostEmploymentDetailTab: typeof import("../domains/skill/components/CostEmploymentDetailTab.vue")['default']
export const LazyCostEmploymentTab: typeof import("../domains/skill/components/CostEmploymentTab.vue")['default']
export const LazyCostExamDetailTab: typeof import("../domains/skill/components/CostExamDetailTab.vue")['default']
export const LazyCostExamTab: typeof import("../domains/skill/components/CostExamTab.vue")['default']
export const LazyCourseRegister: typeof import("../domains/skill/components/CourseRegister.vue")['default']
export const LazyExpenseRegister: typeof import("../domains/skill/components/ExpenseRegister.vue")['default']
export const LazyLanguageRegister: typeof import("../domains/skill/components/LanguageRegister.vue")['default']
export const LazyLicenseRegister: typeof import("../domains/skill/components/LicenseRegister.vue")['default']
export const LazyRoadmap: typeof import("../domains/skill/components/Roadmap.vue")['default']
export const LazyRoadmapBranchStatisticsState: typeof import("../domains/skill/components/RoadmapBranchStatisticsState.vue")['default']
export const LazyScholarshipRegister: typeof import("../domains/skill/components/ScholarshipRegister.vue")['default']
export const LazySkillCourseItem: typeof import("../domains/skill/components/SkillCourseItem.vue")['default']
export const LazySkillCourseListDialog: typeof import("../domains/skill/components/SkillCourseListDialog.vue")['default']
export const LazySupplyLicenseDetailDialog: typeof import("../domains/skill/components/SupplyLicenseDetailDialog.vue")['default']
export const LazySupplyLicenseDialog: typeof import("../domains/skill/components/SupplyLicenseDialog.vue")['default']
export const LazySupportApproval: typeof import("../domains/skill/components/SupportApproval.vue")['default']
export const LazySupportItem: typeof import("../domains/skill/components/SupportItem.vue")['default']
export const LazySupportRegister: typeof import("../domains/skill/components/SupportRegister.vue")['default']
export const LazySupportReject: typeof import("../domains/skill/components/SupportReject.vue")['default']
export const LazyWelfareFeeDialog: typeof import("../domains/skill/components/WelfareFeeDialog.vue")['default']
export const LazyMyLearn: typeof import("../domains/myLearn/components/MyLearn.vue")['default']
export const LazyMyLearnChangeDegreeDialog: typeof import("../domains/myLearn/components/MyLearnChangeDegreeDialog.vue")['default']
export const LazyMyLearnHistory: typeof import("../domains/myLearn/components/MyLearnHistory.vue")['default']
export const LazyMyLearnHistoryPrintDialog: typeof import("../domains/myLearn/components/MyLearnHistoryPrintDialog.vue")['default']
export const LazyMyLearnHistoryTable: typeof import("../domains/myLearn/components/MyLearnHistoryTable.vue")['default']
export const LazyMyLearnMain: typeof import("../domains/myLearn/components/MyLearnMain.vue")['default']
export const LazyMyLearnMainRoadmapChart: typeof import("../domains/myLearn/components/MyLearnMainRoadmapChart.vue")['default']
export const LazyMyLearnMainRoadmapDetailChart: typeof import("../domains/myLearn/components/MyLearnMainRoadmapDetailChart.vue")['default']
export const LazyMyLearnProduct: typeof import("../domains/myLearn/components/MyLearnProduct.vue")['default']
export const LazyMyLearnRepresentativeSkillDialog: typeof import("../domains/myLearn/components/MyLearnRepresentativeSkillDialog.vue")['default']
export const LazyMyLearnReviewDialog: typeof import("../domains/myLearn/components/MyLearnReviewDialog.vue")['default']
export const LazyMyLearnReviewFormDialog: typeof import("../domains/myLearn/components/MyLearnReviewFormDialog.vue")['default']
export const LazyMyLearnReviewItem: typeof import("../domains/myLearn/components/MyLearnReviewItem.vue")['default']
export const LazyMyLearnReviewList: typeof import("../domains/myLearn/components/MyLearnReviewList.vue")['default']
export const LazyMyLearnUserInfoDialog: typeof import("../domains/myLearn/components/MyLearnUserInfoDialog.vue")['default']
export const LazyMileageApplyDialog: typeof import("../domains/mileage/components/MileageApplyDialog.vue")['default']
export const LazyMileageApplyHistoryTab: typeof import("../domains/mileage/components/MileageApplyHistoryTab.vue")['default']
export const LazyMileageHistoryTab: typeof import("../domains/mileage/components/MileageHistoryTab.vue")['default']
export const LazyMain: typeof import("../domains/main/components/Main.vue")['default']
export const LazyMainCourseItem: typeof import("../domains/main/components/MainCourseItem.vue")['default']
export const LazyMainCourseSchedule: typeof import("../domains/main/components/MainCourseSchedule.vue")['default']
export const LazyMainMyCourseDegreeItem: typeof import("../domains/main/components/MainMyCourseDegreeItem.vue")['default']
export const LazyMainMyInfo: typeof import("../domains/main/components/MainMyInfo.vue")['default']
export const LazyMainMyInfoLibraryItem: typeof import("../domains/main/components/MainMyInfoLibraryItem.vue")['default']
export const LazyMainNotice: typeof import("../domains/main/components/MainNotice.vue")['default']
export const LazyMainPopularCourse: typeof import("../domains/main/components/MainPopularCourse.vue")['default']
export const LazyMainPopupDialog: typeof import("../domains/main/components/MainPopupDialog.vue")['default']
export const LazyMainQuestionDialog: typeof import("../domains/main/components/MainQuestionDialog.vue")['default']
export const LazyMainQuickMenu: typeof import("../domains/main/components/MainQuickMenu.vue")['default']
export const LazyMainQuickMenuItem: typeof import("../domains/main/components/MainQuickMenuItem.vue")['default']
export const LazyMainRecentCourse: typeof import("../domains/main/components/MainRecentCourse.vue")['default']
export const LazyMainReview: typeof import("../domains/main/components/MainReview.vue")['default']
export const LazyMainTopBanner: typeof import("../domains/main/components/MainTopBanner.vue")['default']
export const LazySlideBanner: typeof import("../domains/main/components/SlideBanner.vue")['default']
export const LazySlideBannerItem: typeof import("../domains/main/components/SlideBannerItem.vue")['default']
export const LazyAttendanceQrCode: typeof import("../domains/learning/components/AttendanceQrCode.vue")['default']
export const LazyAttendanceQrCodeIntroPage: typeof import("../domains/learning/components/AttendanceQrCodeIntroPage.vue")['default']
export const LazyLearnAttendanceQrCodeDialog: typeof import("../domains/learning/components/LearnAttendanceQrCodeDialog.vue")['default']
export const LazyLearningExternal: typeof import("../domains/learning/components/LearningExternal.vue")['default']
export const LazyLearningGroup: typeof import("../domains/learning/components/LearningGroup.vue")['default']
export const LazyLearningLive: typeof import("../domains/learning/components/LearningLive.vue")['default']
export const LazyLearningMain: typeof import("../domains/learning/components/LearningMain.vue")['default']
export const LazyLearningPdf: typeof import("../domains/learning/components/LearningPdf.vue")['default']
export const LazyLearningReport: typeof import("../domains/learning/components/LearningReport.vue")['default']
export const LazyLearningSurvey: typeof import("../domains/learning/components/LearningSurvey.vue")['default']
export const LazyLearningTest: typeof import("../domains/learning/components/LearningTest.vue")['default']
export const LazyLearningVod: typeof import("../domains/learning/components/LearningVod.vue")['default']
export const LazyStudyRoomMain: typeof import("../domains/learning/components/StudyRoomMain.vue")['default']
export const LazyTitleBar: typeof import("../domains/learning/components/TitleBar.vue")['default']
export const LazyClassRoomApplyTab: typeof import("../domains/facility/components/ClassRoomApplyTab.vue")['default']
export const LazyClassRoomDetailTab: typeof import("../domains/facility/components/ClassRoomDetailTab.vue")['default']
export const LazyFacilityRequestDialog: typeof import("../domains/facility/components/FacilityRequestDialog.vue")['default']
export const LazyResortFacilityRequestDialog: typeof import("../domains/facility/components/ResortFacilityRequestDialog.vue")['default']
export const LazyStudioApplyTab: typeof import("../domains/facility/components/StudioApplyTab.vue")['default']
export const LazyStudioDetailTab: typeof import("../domains/facility/components/StudioDetailTab.vue")['default']
export const LazyStudioRequestDialog: typeof import("../domains/facility/components/StudioRequestDialog.vue")['default']
export const LazyTrainingApplyTab: typeof import("../domains/facility/components/TrainingApplyTab.vue")['default']
export const LazyTrainingDetailTab: typeof import("../domains/facility/components/TrainingDetailTab.vue")['default']
export const LazyCommunity: typeof import("../domains/community/components/Community.vue")['default']
export const LazyCommunityBoardComments: typeof import("../domains/community/components/CommunityBoardComments.vue")['default']
export const LazyCommunityBoardCommentsForm: typeof import("../domains/community/components/CommunityBoardCommentsForm.vue")['default']
export const LazyCommunityBoardCommentsItem: typeof import("../domains/community/components/CommunityBoardCommentsItem.vue")['default']
export const LazyCommunityBoardCommentsItemContents: typeof import("../domains/community/components/CommunityBoardCommentsItemContents.vue")['default']
export const LazyCommunityBoardContentsDetail: typeof import("../domains/community/components/CommunityBoardContentsDetail.vue")['default']
export const LazyCommunityBoardContentsItem: typeof import("../domains/community/components/CommunityBoardContentsItem.vue")['default']
export const LazyCommunitySurveyContentsItem: typeof import("../domains/community/components/CommunitySurveyContentsItem.vue")['default']
export const LazyCommunitySurveyDetailDialog: typeof import("../domains/community/components/CommunitySurveyDetailDialog.vue")['default']
export const LazyAppDownload: typeof import("../domains/auth/components/AppDownload.vue")['default']
export const LazyAuth: typeof import("../domains/auth/components/Auth.vue")['default']
export const LazyPasswordFind: typeof import("../domains/auth/components/PasswordFind.vue")['default']
export const LazyUser: typeof import("../domains/auth/components/User.vue")['default']
export const LazyApproval: typeof import("../domains/approval/components/Approval.vue")['default']
export const LazyApprovalDetail: typeof import("../domains/approval/components/ApprovalDetail.vue")['default']
export const LazyAlertDialog: typeof import("../components/AlertDialog.vue")['default']
export const LazyAppAlert: typeof import("../components/AppAlert.vue")['default']
export const LazyAppConfirm: typeof import("../components/AppConfirm.vue")['default']
export const LazyAppPagination: typeof import("../components/AppPagination.vue")['default']
export const LazyCommonFileUploader: typeof import("../components/CommonFileUploader.vue")['default']
export const LazyCommonQrCode: typeof import("../components/CommonQrCode.vue")['default']
export const LazyFileUploadForm: typeof import("../components/FileUploadForm.vue")['default']
export const LazyFileUploadFormWithDropdown: typeof import("../components/FileUploadFormWithDropdown.vue")['default']
export const LazyLog: typeof import("../components/Log.vue")['default']
export const LazyPageGridWithPaging2: typeof import("../components/PageGridWithPaging2.vue")['default']
export const LazySwiperControls: typeof import("../components/SwiperControls.vue")['default']
export const LazyCustomErrorMessage: typeof import("../components/custom/ErrorMessage.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LazyPubComent: typeof import("../components/pubComent.vue")['default']
export const LazyPubMypageHead: typeof import("../components/pubMypageHead.vue")['default']
export const LazyPubProduct: typeof import("../components/pubProduct.vue")['default']
export const LazyPubProduct02: typeof import("../components/pubProduct02.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtSnackbar: typeof import("../node_modules/nuxt-snackbar/dist/runtime/components/NuxtSnackbar")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
